=== tehmaze/boarddb/board.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/tehmaze/boarddb/board.schema.json",
    "title": "BoardDB",
    "description": "3D-printer control board definitions",
    "type": "object",
    "properties": {
        "manufacturer": {
            "description": "Name of the manufacturer",
            "type": "string"
        },
        "product": {
            "description": "Name of the product",
            "type": "string"
        },
        "version": {
            "description": "Version of the product",
            "type": "string"
        },
        "url": {
            "description": "URL of the product",
            "type": "string"
        },
        "mcu": {
            "description": "Type of micro controller",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "mcuFamily": {
            "description": "Family of micro controller",
            "type": "string"
        },
        "stepstick": {
            "description": "Stepstick slot pin definitions",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {
                        "description": "Label of the stepstick slot",
                        "type": "string"
                    },
                    "enable": {
                        "description": "Enable pin",
                        "type": "string"
                    },
                    "step": {
                        "description": "Step pulse pin",
                        "type": "string"
                    },
                    "dir": {
                        "description": "Direction pin",
                        "type": "string"
                    },
                    "diag": {
                        "description": "DIAG pin (Trinamics specific)",
                        "type": "string"
                    },
                    "cs": {
                        "description": "SPI chip select pin",
                        "type": "string"
                    },
                    "uart": {
                        "description": "UART receive or bidirectional pin",
                        "type": "string"
                    },
                    "uart_tx": {
                        "description": "UART transmit pin",
                        "type": "string"
                    }
                },
                "required": [ "label", "enable", "step", "dir" ]
            },
            "uniqueItems": true
        },
        "endstop": {
            "description": "Endstop pin definitions",
            "type": "object",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "heater": {
            "description": "Heater pin definitions",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {
                        "description": "Label of the stepstick slot",
                        "type": "string"
                    },
                    "pin": {
                        "description": "Pin name",
                        "type": "string"
                    },
                    "max_current": {
                        "description": "Maximum heater current (in ampere)",
                        "type": "number"
                    }
                },
                "required": [ "label", "pin" ]
            },
            "uniqueItems": true
        },
        "sensor": {
            "description": "Sensor pin definitions",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {
                        "description": "Label of the stepstick slot",
                        "type": "string"
                    },
                    "pin": {
                        "description": "Pin name",
                        "type": "string"
                    },
                    "type": {
                        "description": "Sensor type (for hardwired sensors)",
                        "type": "string"
                    },
                    "pullup": {
                        "descriptor": "Pull-up resistor value (in ohm)",
                        "type": "number"
                    }
                },
                "required": [ "label", "pin" ]
            }
        },
        "fan": {
            "description": "Fan pin definitions",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {
                        "description": "Label of the stepstick slot",
                        "type": "string"
                    },
                    "pin": {
                        "description": "Pin name",
                        "type": "string"
                    },
                    "max_current": {
                        "description": "Maximum fan current (in ampere)",
                        "type": "number"
                    }
                },
                "required": [ "label", "pin" ]
            },
            "uniqueItems": true
        }
    },
    "required": [ "manufacturer", "product", "mcu", "mcuFamily", "stepstick", "endstop", "heater", "sensor", "fan" ]
}

=== tehmaze/boarddb/board/bigtreetech/kraken.json
{
    "manufacturer": "BIGTREETECH",
    "product": "Kraken",
    "url": "https://biqu.equipment/collections/new-arrival/products/kraken-for-voron-phoenix",
    "mcuFamily": "STM32",
    "mcu": [
        "stm32h732"
    ],
    "stepstick": [
        {
            "label": "S1",
            "enable": "PE6",
            "step": "PC14",
            "dir": "PC13",
            "cs": "PD6",
            "diag": "PC15",
            "driver": "tmc2160"
        },
        {
            "label": "S2",
            "enable": "PE3",
            "step": "PE5",
            "dir": "PE4",
            "cs": "PD5",
            "diag": "PF0",
            "driver": "tmc2160"
        },
        {
            "label": "S3",
            "enable": "PE0",
            "step": "PE2",
            "dir": "PE1",
            "cs": "PD4",
            "diag": "PF1",
            "driver": "tmc2160"
        },
        {
            "label": "S4",
            "enable": "PB7",
            "step": "PB9",
            "dir": "PB8",
            "cs": "PD3",
            "diag": "PF2",
            "driver": "tmc2160"
        },
        {
            "label": "S5",
            "enable": "PG13",
            "step": "PG9",
            "dir": "PG10",
            "cs": "PD2",
            "diag": "PF3",
            "driver": "tmc2160"
        },
        {
            "label": "S6",
            "enable": "PG12",
            "step": "PG11",
            "dir": "PD7",
            "cs": "PA15",
            "diag": "PF4",
            "driver": "tmc2160"
        },
        {
            "label": "S7",
            "enable": "PB5",
            "step": "PB4",
            "dir": "PB3",
            "cs": "PA9",
            "diag": "PF10",
            "driver": "tmc2160"
        },
        {
            "label": "S8",
            "enable": "PG14",
            "step": "PG15",
            "dir": "PB6",
            "cs": "PA10",
            "diag": "PC0",
            "driver": "tmc2160"
        }
    ],
    "endstop": {
        "MIN1": "PC15",
        "MIN2": "PF0",
        "MIN3": "PF1",
        "MIN4": "PF2",
        "MIN5": "PF3",
        "MIN6": "PF4",
        "MIN7": "PF10",
        "MIN8": "PC0"
    },
    "heater": [
        {
            "label": "BED",
            "pin": "PF5"
        },
        {
            "label": "HE0",
            "pin": "PF6"
        },
        {
            "label": "HE1",
            "pin": "PF7"
        },
        {
            "label": "HE2",
            "pin": "PF9"
        },
        {
            "label": "HE3",
            "pin": "PF8"
        }
    ],
    "sensor": [
        {
            "label": "BED",
            "pin": "PB0"
        },
        {
            "label": "HE0",
            "pin": "PB1"
        },
        {
            "label": "HE1",
            "pin": "PC5"
        },
        {
            "label": "HE2",
            "pin": "PC4"
        },
        {
            "label": "HE3",
            "pin": "PA7"
        }
    ],
    "fan": [
        {
            "label": "FAN0",
            "pin": "PA0"
        },
        {
            "label": "FAN1",
            "pin": "PA1"
        },
        {
            "label": "FAN2",
            "pin": "PA2"
        },
        {
            "label": "FAN3",
            "pin": "PA3"
        },
        {
            "label": "FAN4",
            "pin": "PA4"
        },
        {
            "label": "FAN5",
            "pin": "PA5"
        },
        {
            "label": "FAN6",
            "pin": "PA6",
            "tach_pin": "PC1"
        },
        {
            "label": "FAN7",
            "pin": "PE8",
            "tach_pin": "PG0"
        }
    ]
}

=== tehmaze/boarddb/board/fly/super8pro.json
{
    "manufacturer": "Fly",
    "product": "Super8 Pro",
    "url": "https://github.com/Mellow-3D/Fly-Super8Pro",
    "mcuFamily": "STM32",
    "mcu": [
        "stm32h732"
    ],
    "stepstick": [
        {
            "label": "Drive0",
            "enable": "PF11",
            "step": "PE2",
            "dir": "PC5",
            "cs": "PC4",
            "uart": "PC4"
        },
        {
            "label": "Drive1",
            "enable": "PF14",
            "step": "PE3",
            "dir": "PF13",
            "cs": "PF12",
            "uart": "PF12"
        },
        {
            "label": "Drive2",
            "enable": "PG1",
            "step": "PE4",
            "dir": "PG0",
            "cs": "PF15",
            "uart": "PF15"
        },
        {
            "label": "Drive3",
            "enable": "PE9",
            "step": "PE14",
            "dir": "PE8",
            "cs": "PE7",
            "uart": "PE7"
        },
        {
            "label": "Drive4",
            "enable": "PF2",
            "step": "PE15",
            "dir": "PE11",
            "cs": "PE10",
            "uart": "PE10"
        },
        {
            "label": "Drive5",
            "enable": "PC15",
            "step": "PE1",
            "dir": "PF0",
            "cs": "PF1",
            "uart": "PF1"
        },
        {
            "label": "Drive6",
            "enable": "PG4",
            "step": "PE0",
            "dir": "PG3",
            "cs": "PG2",
            "uart": "PG2"
        },
        {
            "label": "Drive7",
            "enable": "PG7",
            "step": "PE6",
            "dir": "PG6",
            "cs": "PG5",
            "uart": "PG5"
        }
    ],
    "endstop": {
        "IO0": "PG12"
    },
    "heater": [
        {
            "label": "HEAT0",
            "pin": "PB0"
        },
        {
            "label": "HEAT1",
            "pin": "PB1"
        },
        {
            "label": "HEAT2",
            "pin": "PC7"
        },
        {
            "label": "HEAT3",
            "pin": "PF7"
        },
        {
            "label": "HEAT4",
            "pin": "PF6"
        }
    ],
    "sensor": [
        {
            "label": "ADC_0",
            "pin": "PF4"
        },
        {
            "label": "ADC_1",
            "pin": "PF5"
        },
        {
            "label": "ADC_2",
            "pin": "PF9"
        },
        {
            "label": "ADC_3",
            "pin": "PF10"
        },
        {
            "label": "ADC_4",
            "pin": "PC0"
        }
    ],
    "fan": [
        {
            "label": "FAN0",
            "pin": "PA0"
        },
        {
            "label": "FAN1",
            "pin": "PA1"
        },
        {
            "label": "FAN2",
            "pin": "PA2"
        },
        {
            "label": "FAN3",
            "pin": "PA3"
        },
        {
            "label": "FAN4",
            "pin": "PA15"
        },
        {
            "label": "FAN5",
            "pin": "PB11"
        },
        {
            "label": "FAN6",
            "pin": "PB10"
        },
        {
            "label": "FAN7",
            "pin": "PD12"
        },
        {
            "label": "FAN8",
            "pin": "PD14"
        },
        {
            "label": "FAN9",
            "pin": "PD15"
        }
    ]
}
